# This workflow will build and deploy documentation when a release is released

name: docs-manual

on: workflow_dispatch

jobs:
  deploy:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('REQUIREMENTS.txt') }}-${{ hashFiles('./requirements/DEV_REQUIREMENTS.txt') }}-${{ hashFiles('./requirements/S3_REQUIREMENTS.txt') }}-${{ hashFiles('./requirements/TUNE_REQUIREMENTS.txt') }}-${{ hashFiles('./requirements/TEST_EXTRAS_REQUIREMENTS_REQUIREMENTS.txt') }}

    - name: Install dependencies and dev dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[s3,tune]
        pip install -r ./requirements/DEV_REQUIREMENTS.txt
        pip install -r ./requirements/S3_REQUIREMENTS.txt
        pip install -r ./requirements/TUNE_REQUIREMENTS.txt
        pip install -r ./requirements/TEST_EXTRAS_REQUIREMENTS.txt

    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: npm
        cache-dependency-path: website/package-lock.json

    - name: Build website
      working-directory: website
      run: |
        npm ci
        npm run build

    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./website/build
        user_name: github-actions[bot]
        user_email: nicholas.cilfone@fmr.com
